import asyncio
import sys
import traceback
import os
import logging
from dotenv import load_dotenv
from pydantic import ValidationError

# Correct imports as specified
from beeai_framework.agents.bee.agent import BeeAgentExecutionConfig
from beeai_framework.backend.chat import ChatModel
from beeai_framework.backend.message import UserMessage
from beeai_framework.memory import UnconstrainedMemory
from beeai_framework.tools.search.duckduckgo import DuckDuckGoSearchTool
from beeai_framework.tools.weather.openmeteo import OpenMeteoTool
from beeai_framework.workflows.agent import AgentFactoryInput, AgentWorkflow
from beeai_framework.workflows.workflow import WorkflowError

# Configure logging for debugging output
logging.basicConfig(level=logging.DEBUG, format="%(asctime)s - %(levelname)s - %(message)s")

# Load environment variables from .env
load_dotenv()
WATSONX_PROJECT_ID = os.getenv("PROJECT_ID")
WATSONX_API_KEY = os.getenv("WATSONX_API_KEY")
WATSONX_API_URL = os.getenv("WATSONX_URL")


class SimpleMultiAgentSystem:
    """
    A simplified multi-agent system that includes:
      - WeatherForecaster: uses OpenMeteoTool to answer weather-related queries.
      - Solver: aggregates responses using the ChatModel to provide a final answer.
    """

    def __init__(self):
        self.model = None
        self.workflow = None

    async def initialize_model(self):
        logging.debug("Initializing ChatModel...")
        try:
            self.model = await ChatModel.from_name(
                "watsonx:ibm/granite-3-8b-instruct",
                options={
                    "project_id": WATSONX_PROJECT_ID,
                    "api_key": WATSONX_API_KEY,
                    "api_base": WATSONX_API_URL,
                },
            )
            logging.debug("ChatModel initialized successfully.")
        except Exception as e:
            logging.error("Error initializing ChatModel: %s", e, exc_info=True)
            raise

    async def create_workflow(self):
        logging.debug("Creating multi-agent workflow...")
        self.workflow = AgentWorkflow(name="SimpleMultiAgentWorkflow")

        # Weather Forecaster agent (uses OpenMeteoTool)
        self.workflow.add_agent(
            agent=AgentFactoryInput(
                name="WeatherForecaster",
                instructions="You are a weather assistant. Provide accurate weather forecasts only.",
                tools=[OpenMeteoTool()],
                llm=self.model,
                execution=BeeAgentExecutionConfig(max_iterations=3),
            )
        )

        # Solver agent to aggregate the response and include AI advancements
        self.workflow.add_agent(
            agent=AgentFactoryInput(
                name="Solver",
                instructions=(
                    "Based on the previous response, provide a final answer that includes weather details "
                    "and information about the latest AI advancements."
                ),
                llm=self.model,
            )
        )
        logging.debug("Workflow created with WeatherForecaster and Solver agents.")

    async def run_workflow(self, query: str):
        logging.debug("Running workflow for query: %s", query)
        try:
            memory = UnconstrainedMemory()
            # Create a user message without attempting to override its role
            user_msg = UserMessage(content=query)
            await memory.add(user_msg)
            logging.debug("Memory messages: %s", [msg.content for msg in memory.messages])

            response = await self.workflow.run(messages=memory.messages)
            if response and response.state:
                final_answer = response.state.final_answer
                logging.debug("Final Answer: %s", final_answer)
                print("\nFinal Answer:\n", final_answer)
                return final_answer
            else:
                logging.error("No response generated by the workflow.")
                return None

        except WorkflowError as wf_err:
            logging.error("WorkflowError encountered: %s", wf_err, exc_info=True)
        except TypeError as te:
            if "unhashable type: 'ChatModelInput'" in str(te):
                logging.error("Caught unhashable ChatModelInput error. This may be due to internal framework issues.", exc_info=True)
            else:
                logging.error("Unexpected TypeError: %s", te, exc_info=True)
        except Exception as e:
            logging.error("Unexpected error during workflow run: %s", e, exc_info=True)

        return None


async def main():
    system = SimpleMultiAgentSystem()
    try:
        await system.initialize_model()
        await system.create_workflow()
        # Set the combined query:
        query = "What is the weather in Genoa and latest AI advancements?"
        await system.run_workflow(query)
    except (WorkflowError, ValidationError) as e:
        traceback.print_exc()
        sys.exit(str(e))
    except Exception as e:
        traceback.print_exc()
        sys.exit(str(e))


if __name__ == "__main__":
    asyncio.run(main())
