import asyncio
import traceback
import logging
from pydantic import ValidationError

from beeai_framework.agents.bee.agent import BeeAgentExecutionConfig
from beeai_framework.backend.chat import ChatModel
from beeai_framework.backend.message import UserMessage
from beeai_framework.memory import UnconstrainedMemory
from beeai_framework.tools.search.duckduckgo import DuckDuckGoSearchTool
from beeai_framework.tools.weather.openmeteo import OpenMeteoTool
from beeai_framework.workflows.agent import AgentFactoryInput, AgentWorkflow
from beeai_framework.workflows.workflow import WorkflowError

# Configure logging for better debugging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

async def main() -> None:
    logging.info("Initializing Ollama model...")

    try:
        # Initialize Ollama LLM
        llm = await ChatModel.from_name("ollama:granite3.1-dense:8b")
        logging.info("Ollama model loaded successfully.")

        # Create the workflow
        workflow = AgentWorkflow(name="Smart Assistant")

        # Weather Forecaster (uses OpenMeteo)
        workflow.add_agent(
            agent=AgentFactoryInput(
                name="WeatherForecaster",
                instructions="You are a weather assistant. Provide accurate weather forecasts only.",
                tools=[OpenMeteoTool()],
                llm=llm,
                execution=BeeAgentExecutionConfig(max_iterations=3),
            )
        )

        # Researcher (uses DuckDuckGo)
        workflow.add_agent(
            agent=AgentFactoryInput(
                name="Researcher",
                instructions="You are a researcher assistant. Use the tool to find relevant information.",
                tools=[DuckDuckGoSearchTool()],
                llm=llm,
            )
        )

        # Solver (aggregates results)
        workflow.add_agent(
            agent=AgentFactoryInput(
                name="Solver",
                instructions="Your task is to provide the most useful final answer based on the assistants' responses. Ignore irrelevant responses.",
                llm=llm,
            )
        )

        # Define User Query
        prompt = "What is the weather in Genoa, Italy and which day is today"
        memory = UnconstrainedMemory()
        await memory.add(UserMessage(content=prompt))

        # Execute Workflow
        logging.info("Executing Smart Assistant workflow...")
        response = await workflow.run(messages=memory.messages)

        # Print the result
        if response and response.state:
            logging.info(f"🔍 Final Assistant Response: {response.state.final_answer}")
            print("\n🔍 AI Assistant Response:\n", response.state.final_answer)
        else:
            logging.warning("No response generated by the workflow.")

    except WorkflowError:
        logging.error("WorkflowError encountered:", exc_info=True)
    except ValidationError:
        logging.error("ValidationError encountered:", exc_info=True)
    except Exception as e:
        logging.error(f"Unexpected error: {e}", exc_info=True)


if __name__ == "__main__":
    asyncio.run(main())
