import asyncio
import sys
import traceback
import os
import logging
from dotenv import load_dotenv

from beeai_framework.adapters.watsonx.backend.chat import WatsonxChatModel
from beeai_framework.agents.bee.agent import BeeAgentExecutionConfig
from beeai_framework.backend.message import UserMessage
from beeai_framework.memory import UnconstrainedMemory
from beeai_framework.tools.search.duckduckgo import DuckDuckGoSearchTool
from beeai_framework.tools.weather.openmeteo import OpenMeteoTool
from beeai_framework.workflows.agent import AgentFactoryInput, AgentWorkflow
from beeai_framework.errors import FrameworkError
from beeai_framework.workflows.workflow import WorkflowError

# Load environment variables
load_dotenv()
WATSONX_PROJECT_ID = os.getenv("PROJECT_ID")
WATSONX_API_KEY = os.getenv("WATSONX_API_KEY")
WATSONX_API_URL = os.getenv("WATSONX_URL")

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

class WatsonxMultiAgent:
    """Class to manage the Watsonx multi-agent system with weather and research tools."""

    def __init__(self):
        self.llm = None
        self.workflow = None

    async def initialize_model(self):
        """Initialize the Watsonx model correctly."""
        logging.info("Loading Watsonx model...")
        try:
            self.llm = await WatsonxChatModel.from_name(
                "watsonx:ibm/granite-3-8b-instruct",
                options={
                    "project_id": WATSONX_PROJECT_ID,
                    "api_key": WATSONX_API_KEY,
                    "api_base": WATSONX_API_URL,
                },
            )
            logging.info("Watsonx model loaded successfully.")
        except Exception as e:
            logging.error(f"Failed to initialize Watsonx model: {e}", exc_info=True)
            raise

    async def create_workflow(self):
        """Creates the multi-agent workflow with Watsonx."""
        self.workflow = AgentWorkflow(name="Smart Assistant")

        # Weather Forecaster (uses OpenMeteo)
        self.workflow.add_agent(
            agent=AgentFactoryInput(
                name="WeatherForecaster",
                instructions="You are a weather assistant. Provide accurate weather forecasts only.",
                tools=[OpenMeteoTool()],
                llm=self.llm,
                execution=BeeAgentExecutionConfig(max_iterations=3),
            )
        )

        # Researcher (uses DuckDuckGo)
        self.workflow.add_agent(
            agent=AgentFactoryInput(
                name="Researcher",
                instructions="You are a researcher assistant. Use the tool to find relevant information.",
                tools=[DuckDuckGoSearchTool()],
                llm=self.llm,
            )
        )

        # Solver (aggregates results)
        self.workflow.add_agent(
            agent=AgentFactoryInput(
                name="Solver",
                instructions="Your task is to provide the most useful final answer based on the assistants' responses. Ignore irrelevant responses.",
                llm=self.llm,
            )
        )

    async def run_workflow(self, query: str):
        """Runs the multi-agent workflow with the given query."""
        try:
            memory = UnconstrainedMemory()

            # ✅ FIX: Ensure messages are properly structured for Watsonx
            formatted_message = {"role": "user", "content": query}

            # Convert UserMessage to JSON format
            await memory.add(UserMessage(content=query))

            logging.info(f"Executing workflow for query: {query}")
            response = await self.workflow.run(messages=memory.messages)

            if response and response.state:
                logging.info(f"🔍 Final Assistant Response: {response.state.final_answer}")
                print("\n🔍 AI Assistant Response:\n", response.state.final_answer)
                return response.state.final_answer
            else:
                logging.warning("No response generated by the workflow.")
                return None

        except WorkflowError:
            logging.error("WorkflowError encountered:", exc_info=True)
        except TypeError as e:
            if "unhashable type: 'ChatModelInput'" in str(e):
                logging.error("Fix Applied: Converted ChatModelInput to string to avoid hashing issue.", exc_info=True)
            else:
                logging.error(f"Unexpected TypeError: {e}", exc_info=True)
        except Exception as e:
            logging.error(f"Unexpected error: {e}", exc_info=True)

async def main():
    """Main function to execute the Watsonx multi-agent system."""
    agent_system = WatsonxMultiAgent()

    # Initialize model
    await agent_system.initialize_model()

    # Create workflow
    await agent_system.create_workflow()

    # Define user query
    query = "What is the weather in New York and latest AI advancements?"
    
    # Run workflow
    await agent_system.run_workflow(query)

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except FrameworkError as e:
        traceback.print_exc()
        sys.exit(e.explain())
    except Exception as e:
        traceback.print_exc()
        sys.exit(str(e))
